### ISSUE TITLE
需要帮助：获取今年生日的阳历日期

### ISSUE THREAD

**Issue by allinu** [kinegratii/borax#47]
目前打算开发一个生日计算功能的小脚本，根据阳历出生年月日，然后推算今年什么时候过阴历生日，目前试了很多的农历Python库，但是没有找到一个很好的解决办法，而且还涉及到闰月的情况，我还不太清楚闰月发生时，是要过两个生日么？

- 根据出生年月日计算今年阴历生日
- 当所处年份的生日月份存在闰月时如何处理

希望有能力的人能够帮助我一下，不胜感激 🙏

**Comment by fastpx2014** [comment]
1. borax 可以解决 *根据阳历(公历)生日计算在今天阴历(农历)生日*  ，使用 `LunarFestival` 类即可
2. 在现实生活中，有的只过一个生日，有的有过两个生日，都存在。
3. 在编程实现中，可以也返回闰月的那个生日，毕竟同一个闰月出现比较少，最近闰四月是在2001、2012、2020、2058；也可以提供一个变量（如下面的leap_day_included ），控制是否显示闰月生日。

有关代码如下：

```python
from datetime import date
from borax.calendars.lunardate import LunarDate
from borax.calendars.festivals2 import LunarFestival, Period

  solar_birth = date(1994, 5, 21)
  lunar_birth = LunarDate.from_solar(solar_birth) # 出生那天的农历日期
  print(lunar_birth)  # LunarDate(1994, 4, 11, 0)

  # 农历生日对应的节日对象
  lunar_birth_festival = LunarFestival(month=lunar_birth.month, day=lunar_birth.day)

  # [<WrappedDate:2020-05-03(二〇二〇年四月十一)>, <WrappedDate:2020-06-02(二〇二〇年闰四月十一)>]
  wd_list = lunar_birth_festival.list_days(*Period.lunar_year(2020))

  leap_day_included = True
  if not leap_day_included:
      wd_list = [wd for wd in wd_list if wd.lunar.leap == 0] # 去掉其中的闰月日期
  print(wd_list)
```

文档：https://borax.readthedocs.io/zh_CN/latest/guides/festivals2/

**Comment by allinu** [comment]
收到，谢谢 @fastpx2014  🙏 🌹
