### ISSUE TITLE
[新版本]Borax 4.1.0

### ISSUE THREAD

**Issue by kinegratii** [kinegratii/borax#53]
Borax 4.1.0 是一个重大更新的版本，主要包括：

- **python版本最低要求为3.9** ，不再支持python3.7和3.8
- 使用 *pyproject.toml* 文件作为项目构建配置文件
- 更新开发依赖包至最新版本，如flake8、nose2、pylint等
- 新增基于 tkinter 的日历应用程序

预计发布时间：2024年1月

**Comment by pystraf** [comment]
发布了吧，close掉
